# Generated by Django 5.2 on 2025-05-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_is_completed_task_priority_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
